# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='service/toon/toon_external.proto',
  package='bnet.protocol.toon.external',
  serialized_pb='\n service/toon/toon_external.proto\x12\x1b\x62net.protocol.toon.external\x1a\x11lib/rpc/rpc.proto\x1a\x19lib/protocol/entity.proto\x1a\x1clib/protocol/attribute.proto\x1a\x17service/toon/toon.proto\"\x11\n\x0fToonListRequest\":\n\x10ToonListResponse\x12&\n\x05toons\x18\x02 \x03(\x0b\x32\x17.bnet.protocol.EntityId\":\n\x11SelectToonRequest\x12%\n\x04toon\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\"\x14\n\x12SelectToonResponse\"X\n\x11\x43reateToonRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x35\n\tattribute\x18\x02 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\";\n\x12\x43reateToonResponse\x12%\n\x04toon\x18\x02 \x01(\x0b\x32\x17.bnet.protocol.EntityId\":\n\x11\x44\x65leteToonRequest\x12%\n\x04toon\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\"\x14\n\x12\x44\x65leteToonResponse2\xcb\x03\n\x13ToonServiceExternal\x12g\n\x08ToonList\x12,.bnet.protocol.toon.external.ToonListRequest\x1a-.bnet.protocol.toon.external.ToonListResponse\x12m\n\nSelectToon\x12..bnet.protocol.toon.external.SelectToonRequest\x1a/.bnet.protocol.toon.external.SelectToonResponse\x12m\n\nCreateToon\x12..bnet.protocol.toon.external.CreateToonRequest\x1a/.bnet.protocol.toon.external.CreateToonResponse\x12m\n\nDeleteToon\x12..bnet.protocol.toon.external.DeleteToonRequest\x1a/.bnet.protocol.toon.external.DeleteToonResponseB\x03\x80\x01\x01')




_TOONLISTREQUEST = descriptor.Descriptor(
  name='ToonListRequest',
  full_name='bnet.protocol.toon.external.ToonListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=166,
  serialized_end=183,
)


_TOONLISTRESPONSE = descriptor.Descriptor(
  name='ToonListResponse',
  full_name='bnet.protocol.toon.external.ToonListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='toons', full_name='bnet.protocol.toon.external.ToonListResponse.toons', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=185,
  serialized_end=243,
)


_SELECTTOONREQUEST = descriptor.Descriptor(
  name='SelectToonRequest',
  full_name='bnet.protocol.toon.external.SelectToonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='toon', full_name='bnet.protocol.toon.external.SelectToonRequest.toon', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=245,
  serialized_end=303,
)


_SELECTTOONRESPONSE = descriptor.Descriptor(
  name='SelectToonResponse',
  full_name='bnet.protocol.toon.external.SelectToonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=305,
  serialized_end=325,
)


_CREATETOONREQUEST = descriptor.Descriptor(
  name='CreateToonRequest',
  full_name='bnet.protocol.toon.external.CreateToonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.toon.external.CreateToonRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.toon.external.CreateToonRequest.attribute', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=327,
  serialized_end=415,
)


_CREATETOONRESPONSE = descriptor.Descriptor(
  name='CreateToonResponse',
  full_name='bnet.protocol.toon.external.CreateToonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='toon', full_name='bnet.protocol.toon.external.CreateToonResponse.toon', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=417,
  serialized_end=476,
)


_DELETETOONREQUEST = descriptor.Descriptor(
  name='DeleteToonRequest',
  full_name='bnet.protocol.toon.external.DeleteToonRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='toon', full_name='bnet.protocol.toon.external.DeleteToonRequest.toon', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=478,
  serialized_end=536,
)


_DELETETOONRESPONSE = descriptor.Descriptor(
  name='DeleteToonResponse',
  full_name='bnet.protocol.toon.external.DeleteToonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=538,
  serialized_end=558,
)

import lib.rpc.rpc_pb2
import lib.protocol.entity_pb2
import lib.protocol.attribute_pb2
import service.toon.toon_pb2

_TOONLISTRESPONSE.fields_by_name['toons'].message_type = lib.protocol.entity_pb2._ENTITYID
_SELECTTOONREQUEST.fields_by_name['toon'].message_type = lib.protocol.entity_pb2._ENTITYID
_CREATETOONREQUEST.fields_by_name['attribute'].message_type = lib.protocol.attribute_pb2._ATTRIBUTE
_CREATETOONRESPONSE.fields_by_name['toon'].message_type = lib.protocol.entity_pb2._ENTITYID
_DELETETOONREQUEST.fields_by_name['toon'].message_type = lib.protocol.entity_pb2._ENTITYID

class ToonListRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOONLISTREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.ToonListRequest)

class ToonListResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOONLISTRESPONSE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.ToonListResponse)

class SelectToonRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SELECTTOONREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.SelectToonRequest)

class SelectToonResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SELECTTOONRESPONSE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.SelectToonResponse)

class CreateToonRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATETOONREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.CreateToonRequest)

class CreateToonResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CREATETOONRESPONSE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.CreateToonResponse)

class DeleteToonRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETETOONREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.DeleteToonRequest)

class DeleteToonResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DELETETOONRESPONSE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.toon.external.DeleteToonResponse)


_TOONSERVICEEXTERNAL = descriptor.ServiceDescriptor(
  name='ToonServiceExternal',
  full_name='bnet.protocol.toon.external.ToonServiceExternal',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=561,
  serialized_end=1020,
  methods=[
  descriptor.MethodDescriptor(
    name='ToonList',
    full_name='bnet.protocol.toon.external.ToonServiceExternal.ToonList',
    index=0,
    containing_service=None,
    input_type=_TOONLISTREQUEST,
    output_type=_TOONLISTRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='SelectToon',
    full_name='bnet.protocol.toon.external.ToonServiceExternal.SelectToon',
    index=1,
    containing_service=None,
    input_type=_SELECTTOONREQUEST,
    output_type=_SELECTTOONRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='CreateToon',
    full_name='bnet.protocol.toon.external.ToonServiceExternal.CreateToon',
    index=2,
    containing_service=None,
    input_type=_CREATETOONREQUEST,
    output_type=_CREATETOONRESPONSE,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='DeleteToon',
    full_name='bnet.protocol.toon.external.ToonServiceExternal.DeleteToon',
    index=3,
    containing_service=None,
    input_type=_DELETETOONREQUEST,
    output_type=_DELETETOONRESPONSE,
    options=None,
  ),
])
'''
class ToonServiceExternal(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TOONSERVICEEXTERNAL
class ToonServiceExternal_Stub(ToonServiceExternal):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TOONSERVICEEXTERNAL

# @@protoc_insertion_point(module_scope)
'''