# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='lib/config/process_config.proto',
  package='bnet.protocol.config',
  serialized_pb='\n\x1flib/config/process_config.proto\x12\x14\x62net.protocol.config\x1a\x11lib/rpc/rpc.proto\"\"\n\x03Var\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"%\n\x08Resource\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03url\x18\x02 \x02(\t\"C\n\x10ProgramResources\x12/\n\x07program\x18\x01 \x03(\x0b\x32\x1e.bnet.protocol.config.Resource\"c\n\rServerAddress\x12\'\n\x07\x61\x64\x64ress\x18\x01 \x02(\x0b\x32\x16.bnet.protocol.Address\x12\x14\n\x0cprocess_name\x18\x02 \x02(\t\x12\x13\n\x0bserver_name\x18\x03 \x01(\t\"|\n\tServerSet\x12;\n\x0eserver_address\x18\x01 \x03(\x0b\x32#.bnet.protocol.config.ServerAddress\x12\x18\n\x10\x65xported_service\x18\x02 \x03(\t\x12\x18\n\x10imported_service\x18\x03 \x03(\t\"1\n\x13SupplementalService\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04port\x18\x02 \x02(\r\"f\n\x0bListenPoint\x12\x0c\n\x04port\x18\x01 \x02(\r\x12\x18\n\x07\x61\x64\x64ress\x18\x02 \x01(\t:\x07\x30.0.0.0\x12/\n\x06\x61\x63\x63\x65pt\x18\x03 \x03(\x0b\x32\x1f.bnet.protocol.config.ServerSet\"$\n\x0cServiceShard\x12\x14\n\x0cprocess_name\x18\x01 \x02(\t\"]\n\rServiceConfig\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03url\x18\x02 \x02(\t\x12\x31\n\x05shard\x18\x03 \x03(\x0b\x32\".bnet.protocol.config.ServiceShard\"\x84\x01\n\x0fRPCServerConfig\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x31\n\x06listen\x18\x02 \x01(\x0b\x32!.bnet.protocol.config.ListenPoint\x12\x30\n\x07\x63onnect\x18\x03 \x03(\x0b\x32\x1f.bnet.protocol.config.ServerSet\"\xb5\x02\n\rProcessConfig\x12\x14\n\x0cprocess_name\x18\x01 \x02(\t\x12\x35\n\x06server\x18\x02 \x03(\x0b\x32%.bnet.protocol.config.RPCServerConfig\x12\x30\n\x08resource\x18\x03 \x03(\x0b\x32\x1e.bnet.protocol.config.Resource\x12\x34\n\x07service\x18\x04 \x03(\x0b\x32#.bnet.protocol.config.ServiceConfig\x12&\n\x03var\x18\x05 \x03(\x0b\x32\x19.bnet.protocol.config.Var\x12G\n\x14supplemental_service\x18\x06 \x03(\x0b\x32).bnet.protocol.config.SupplementalServiceB\x10\x42\x0e\x43ProcessConfig')




_VAR = descriptor.Descriptor(
  name='Var',
  full_name='bnet.protocol.config.Var',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.config.Var.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='bnet.protocol.config.Var.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=76,
  serialized_end=110,
)


_RESOURCE = descriptor.Descriptor(
  name='Resource',
  full_name='bnet.protocol.config.Resource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.config.Resource.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='bnet.protocol.config.Resource.url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=112,
  serialized_end=149,
)


_PROGRAMRESOURCES = descriptor.Descriptor(
  name='ProgramResources',
  full_name='bnet.protocol.config.ProgramResources',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='program', full_name='bnet.protocol.config.ProgramResources.program', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=151,
  serialized_end=218,
)


_SERVERADDRESS = descriptor.Descriptor(
  name='ServerAddress',
  full_name='bnet.protocol.config.ServerAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='address', full_name='bnet.protocol.config.ServerAddress.address', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='process_name', full_name='bnet.protocol.config.ServerAddress.process_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server_name', full_name='bnet.protocol.config.ServerAddress.server_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=220,
  serialized_end=319,
)


_SERVERSET = descriptor.Descriptor(
  name='ServerSet',
  full_name='bnet.protocol.config.ServerSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='server_address', full_name='bnet.protocol.config.ServerSet.server_address', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='exported_service', full_name='bnet.protocol.config.ServerSet.exported_service', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='imported_service', full_name='bnet.protocol.config.ServerSet.imported_service', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=321,
  serialized_end=445,
)


_SUPPLEMENTALSERVICE = descriptor.Descriptor(
  name='SupplementalService',
  full_name='bnet.protocol.config.SupplementalService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.config.SupplementalService.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='port', full_name='bnet.protocol.config.SupplementalService.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=447,
  serialized_end=496,
)


_LISTENPOINT = descriptor.Descriptor(
  name='ListenPoint',
  full_name='bnet.protocol.config.ListenPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='port', full_name='bnet.protocol.config.ListenPoint.port', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='address', full_name='bnet.protocol.config.ListenPoint.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("0.0.0.0", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='accept', full_name='bnet.protocol.config.ListenPoint.accept', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=498,
  serialized_end=600,
)


_SERVICESHARD = descriptor.Descriptor(
  name='ServiceShard',
  full_name='bnet.protocol.config.ServiceShard',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='process_name', full_name='bnet.protocol.config.ServiceShard.process_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=602,
  serialized_end=638,
)


_SERVICECONFIG = descriptor.Descriptor(
  name='ServiceConfig',
  full_name='bnet.protocol.config.ServiceConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.config.ServiceConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='url', full_name='bnet.protocol.config.ServiceConfig.url', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='shard', full_name='bnet.protocol.config.ServiceConfig.shard', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=640,
  serialized_end=733,
)


_RPCSERVERCONFIG = descriptor.Descriptor(
  name='RPCServerConfig',
  full_name='bnet.protocol.config.RPCServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='name', full_name='bnet.protocol.config.RPCServerConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='listen', full_name='bnet.protocol.config.RPCServerConfig.listen', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='connect', full_name='bnet.protocol.config.RPCServerConfig.connect', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=736,
  serialized_end=868,
)


_PROCESSCONFIG = descriptor.Descriptor(
  name='ProcessConfig',
  full_name='bnet.protocol.config.ProcessConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='process_name', full_name='bnet.protocol.config.ProcessConfig.process_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='server', full_name='bnet.protocol.config.ProcessConfig.server', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resource', full_name='bnet.protocol.config.ProcessConfig.resource', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='service', full_name='bnet.protocol.config.ProcessConfig.service', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='var', full_name='bnet.protocol.config.ProcessConfig.var', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='supplemental_service', full_name='bnet.protocol.config.ProcessConfig.supplemental_service', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=871,
  serialized_end=1180,
)

import lib.rpc.rpc_pb2

_PROGRAMRESOURCES.fields_by_name['program'].message_type = _RESOURCE
_SERVERADDRESS.fields_by_name['address'].message_type = lib.rpc.rpc_pb2._ADDRESS
_SERVERSET.fields_by_name['server_address'].message_type = _SERVERADDRESS
_LISTENPOINT.fields_by_name['accept'].message_type = _SERVERSET
_SERVICECONFIG.fields_by_name['shard'].message_type = _SERVICESHARD
_RPCSERVERCONFIG.fields_by_name['listen'].message_type = _LISTENPOINT
_RPCSERVERCONFIG.fields_by_name['connect'].message_type = _SERVERSET
_PROCESSCONFIG.fields_by_name['server'].message_type = _RPCSERVERCONFIG
_PROCESSCONFIG.fields_by_name['resource'].message_type = _RESOURCE
_PROCESSCONFIG.fields_by_name['service'].message_type = _SERVICECONFIG
_PROCESSCONFIG.fields_by_name['var'].message_type = _VAR
_PROCESSCONFIG.fields_by_name['supplemental_service'].message_type = _SUPPLEMENTALSERVICE

class Var(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VAR
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.Var)

class Resource(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESOURCE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.Resource)

class ProgramResources(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROGRAMRESOURCES
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.ProgramResources)

class ServerAddress(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERADDRESS
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.ServerAddress)

class ServerSet(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERSET
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.ServerSet)

class SupplementalService(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUPPLEMENTALSERVICE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.SupplementalService)

class ListenPoint(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LISTENPOINT
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.ListenPoint)

class ServiceShard(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICESHARD
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.ServiceShard)

class ServiceConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICECONFIG
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.ServiceConfig)

class RPCServerConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPCSERVERCONFIG
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.RPCServerConfig)

class ProcessConfig(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PROCESSCONFIG
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.config.ProcessConfig)

# @@protoc_insertion_point(module_scope)
