# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='service/presence/presence.proto',
  package='bnet.protocol.presence',
  serialized_pb='\n\x1fservice/presence/presence.proto\x12\x16\x62net.protocol.presence\x1a\x1clib/protocol/attribute.proto\x1a\x19lib/protocol/entity.proto\x1a\x11lib/rpc/rpc.proto\x1a%service/presence/presence_types.proto\"|\n\x10SubscribeRequest\x12)\n\x08\x61gent_id\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12*\n\tentity_id\x18\x02 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12\x11\n\tobject_id\x18\x03 \x02(\x04\"k\n\x12UnsubscribeRequest\x12)\n\x08\x61gent_id\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12*\n\tentity_id\x18\x02 \x02(\x0b\x32\x17.bnet.protocol.EntityId\"|\n\rUpdateRequest\x12*\n\tentity_id\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12?\n\x0f\x66ield_operation\x18\x02 \x03(\x0b\x32&.bnet.protocol.presence.FieldOperation\"i\n\x0cQueryRequest\x12*\n\tentity_id\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12-\n\x03key\x18\x02 \x03(\x0b\x32 .bnet.protocol.presence.FieldKey\"=\n\rQueryResponse\x12,\n\x05\x66ield\x18\x02 \x03(\x0b\x32\x1d.bnet.protocol.presence.Field2\xcf\x02\n\x0fPresenceService\x12L\n\tSubscribe\x12(.bnet.protocol.presence.SubscribeRequest\x1a\x15.bnet.protocol.NoData\x12P\n\x0bUnsubscribe\x12*.bnet.protocol.presence.UnsubscribeRequest\x1a\x15.bnet.protocol.NoData\x12\x46\n\x06Update\x12%.bnet.protocol.presence.UpdateRequest\x1a\x15.bnet.protocol.NoData\x12T\n\x05Query\x12$.bnet.protocol.presence.QueryRequest\x1a%.bnet.protocol.presence.QueryResponseB\x03\x80\x01\x01')




_SUBSCRIBEREQUEST = descriptor.Descriptor(
  name='SubscribeRequest',
  full_name='bnet.protocol.presence.SubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='agent_id', full_name='bnet.protocol.presence.SubscribeRequest.agent_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.presence.SubscribeRequest.entity_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='object_id', full_name='bnet.protocol.presence.SubscribeRequest.object_id', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=174,
  serialized_end=298,
)


_UNSUBSCRIBEREQUEST = descriptor.Descriptor(
  name='UnsubscribeRequest',
  full_name='bnet.protocol.presence.UnsubscribeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='agent_id', full_name='bnet.protocol.presence.UnsubscribeRequest.agent_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.presence.UnsubscribeRequest.entity_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=300,
  serialized_end=407,
)


_UPDATEREQUEST = descriptor.Descriptor(
  name='UpdateRequest',
  full_name='bnet.protocol.presence.UpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.presence.UpdateRequest.entity_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='field_operation', full_name='bnet.protocol.presence.UpdateRequest.field_operation', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=409,
  serialized_end=533,
)


_QUERYREQUEST = descriptor.Descriptor(
  name='QueryRequest',
  full_name='bnet.protocol.presence.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.presence.QueryRequest.entity_id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='bnet.protocol.presence.QueryRequest.key', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=535,
  serialized_end=640,
)


_QUERYRESPONSE = descriptor.Descriptor(
  name='QueryResponse',
  full_name='bnet.protocol.presence.QueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='field', full_name='bnet.protocol.presence.QueryResponse.field', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=642,
  serialized_end=703,
)

import lib.protocol.attribute_pb2
import lib.protocol.entity_pb2
import lib.rpc.rpc_pb2
import service.presence.presence_types_pb2

_SUBSCRIBEREQUEST.fields_by_name['agent_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_SUBSCRIBEREQUEST.fields_by_name['entity_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_UNSUBSCRIBEREQUEST.fields_by_name['agent_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_UNSUBSCRIBEREQUEST.fields_by_name['entity_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_UPDATEREQUEST.fields_by_name['entity_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_UPDATEREQUEST.fields_by_name['field_operation'].message_type = service.presence.presence_types_pb2._FIELDOPERATION
_QUERYREQUEST.fields_by_name['entity_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_QUERYREQUEST.fields_by_name['key'].message_type = service.presence.presence_types_pb2._FIELDKEY
_QUERYRESPONSE.fields_by_name['field'].message_type = service.presence.presence_types_pb2._FIELD

class SubscribeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBSCRIBEREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.SubscribeRequest)

class UnsubscribeRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNSUBSCRIBEREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.UnsubscribeRequest)

class UpdateRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.UpdateRequest)

class QueryRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.QueryRequest)

class QueryResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUERYRESPONSE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.QueryResponse)


_PRESENCESERVICE = descriptor.ServiceDescriptor(
  name='PresenceService',
  full_name='bnet.protocol.presence.PresenceService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=706,
  serialized_end=1041,
  methods=[
  descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='bnet.protocol.presence.PresenceService.Subscribe',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBEREQUEST,
    output_type=lib.rpc.rpc_pb2._NODATA,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Unsubscribe',
    full_name='bnet.protocol.presence.PresenceService.Unsubscribe',
    index=1,
    containing_service=None,
    input_type=_UNSUBSCRIBEREQUEST,
    output_type=lib.rpc.rpc_pb2._NODATA,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Update',
    full_name='bnet.protocol.presence.PresenceService.Update',
    index=2,
    containing_service=None,
    input_type=_UPDATEREQUEST,
    output_type=lib.rpc.rpc_pb2._NODATA,
    options=None,
  ),
  descriptor.MethodDescriptor(
    name='Query',
    full_name='bnet.protocol.presence.PresenceService.Query',
    index=3,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYRESPONSE,
    options=None,
  ),
])
'''
class PresenceService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _PRESENCESERVICE
class PresenceService_Stub(PresenceService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _PRESENCESERVICE

# @@protoc_insertion_point(module_scope)
'''