# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='service/presence/presence_types.proto',
  package='bnet.protocol.presence',
  serialized_pb='\n%service/presence/presence_types.proto\x12\x16\x62net.protocol.presence\x1a\x1clib/protocol/attribute.proto\x1a\x19lib/protocol/entity.proto\x1a#service/channel/channel_types.proto\"K\n\x08\x46ieldKey\x12\x0f\n\x07program\x18\x01 \x02(\r\x12\r\n\x05group\x18\x02 \x02(\r\x12\r\n\x05\x66ield\x18\x03 \x02(\r\x12\x10\n\x05index\x18\x04 \x01(\x04:\x01\x30\"g\n\x05\x46ield\x12-\n\x03key\x18\x01 \x02(\x0b\x32 .bnet.protocol.presence.FieldKey\x12/\n\x05value\x18\x02 \x02(\x0b\x32 .bnet.protocol.attribute.Variant\"\xb1\x01\n\x0e\x46ieldOperation\x12,\n\x05\x66ield\x18\x01 \x02(\x0b\x32\x1d.bnet.protocol.presence.Field\x12L\n\toperation\x18\x02 \x01(\x0e\x32\x34.bnet.protocol.presence.FieldOperation.OperationType:\x03SET\"#\n\rOperationType\x12\x07\n\x03SET\x10\x00\x12\t\n\x05\x43LEAR\x10\x01\"\xd8\x01\n\x0c\x43hannelState\x12*\n\tentity_id\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12?\n\x0f\x66ield_operation\x18\x02 \x03(\x0b\x32&.bnet.protocol.presence.FieldOperation2[\n\x08presence\x12#.bnet.protocol.channel.ChannelState\x18\x65 \x01(\x0b\x32$.bnet.protocol.presence.ChannelState')



_FIELDOPERATION_OPERATIONTYPE = descriptor.EnumDescriptor(
  name='OperationType',
  full_name='bnet.protocol.presence.FieldOperation.OperationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SET', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CLEAR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=484,
  serialized_end=519,
)


_FIELDKEY = descriptor.Descriptor(
  name='FieldKey',
  full_name='bnet.protocol.presence.FieldKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='program', full_name='bnet.protocol.presence.FieldKey.program', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='group', full_name='bnet.protocol.presence.FieldKey.group', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='field', full_name='bnet.protocol.presence.FieldKey.field', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='index', full_name='bnet.protocol.presence.FieldKey.index', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=159,
  serialized_end=234,
)


_FIELD = descriptor.Descriptor(
  name='Field',
  full_name='bnet.protocol.presence.Field',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='bnet.protocol.presence.Field.key', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='bnet.protocol.presence.Field.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=236,
  serialized_end=339,
)


_FIELDOPERATION = descriptor.Descriptor(
  name='FieldOperation',
  full_name='bnet.protocol.presence.FieldOperation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='field', full_name='bnet.protocol.presence.FieldOperation.field', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='operation', full_name='bnet.protocol.presence.FieldOperation.operation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIELDOPERATION_OPERATIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=342,
  serialized_end=519,
)


_CHANNELSTATE = descriptor.Descriptor(
  name='ChannelState',
  full_name='bnet.protocol.presence.ChannelState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='entity_id', full_name='bnet.protocol.presence.ChannelState.entity_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='field_operation', full_name='bnet.protocol.presence.ChannelState.field_operation', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='presence', full_name='bnet.protocol.presence.ChannelState.presence', index=0,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=522,
  serialized_end=738,
)

import lib.protocol.attribute_pb2
import lib.protocol.entity_pb2
import service.channel.channel_types_pb2

_FIELD.fields_by_name['key'].message_type = _FIELDKEY
_FIELD.fields_by_name['value'].message_type = lib.protocol.attribute_pb2._VARIANT
_FIELDOPERATION.fields_by_name['field'].message_type = _FIELD
_FIELDOPERATION.fields_by_name['operation'].enum_type = _FIELDOPERATION_OPERATIONTYPE
_FIELDOPERATION_OPERATIONTYPE.containing_type = _FIELDOPERATION;
_CHANNELSTATE.fields_by_name['entity_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_CHANNELSTATE.fields_by_name['field_operation'].message_type = _FIELDOPERATION

class FieldKey(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIELDKEY
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.FieldKey)

class Field(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIELD
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.Field)

class FieldOperation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FIELDOPERATION
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.FieldOperation)

class ChannelState(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHANNELSTATE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.presence.ChannelState)

_CHANNELSTATE.extensions_by_name['presence'].message_type = _CHANNELSTATE
service.channel.channel_types_pb2.ChannelState.RegisterExtension(_CHANNELSTATE.extensions_by_name['presence'])
# @@protoc_insertion_point(module_scope)
