# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='service/server_pool/server_pool.proto',
  package='bnet.protocol.server_pool',
  serialized_pb='\n%service/server_pool/server_pool.proto\x12\x19\x62net.protocol.server_pool\x1a\x1clib/protocol/attribute.proto\x1a\x11lib/rpc/rpc.proto\"\x10\n\x0eGetLoadRequest\"V\n\x0bServerState\x12\x17\n\x0c\x63urrent_load\x18\x01 \x01(\x02:\x01\x31\x12\x15\n\ngame_count\x18\x02 \x01(\x05:\x01\x30\x12\x17\n\x0cplayer_count\x18\x03 \x01(\x05:\x01\x30\"\xce\x01\n\nServerInfo\x12&\n\x04host\x18\x01 \x02(\x0b\x32\x18.bnet.protocol.ProcessId\x12\x16\n\x07replace\x18\x02 \x01(\x08:\x05\x66\x61lse\x12\x35\n\x05state\x18\x03 \x01(\x0b\x32&.bnet.protocol.server_pool.ServerState\x12\x35\n\tattribute\x18\x04 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\x12\x12\n\nprogram_id\x18\x05 \x01(\x07\"\x12\n\x10PoolStateRequest\"H\n\x11PoolStateResponse\x12\x33\n\x04info\x18\x01 \x03(\x0b\x32%.bnet.protocol.server_pool.ServerInfo2~\n\x11ServerPoolService\x12i\n\x0cGetPoolState\x12+.bnet.protocol.server_pool.PoolStateRequest\x1a,.bnet.protocol.server_pool.PoolStateResponseB\x03\x80\x01\x01')




_GETLOADREQUEST = descriptor.Descriptor(
  name='GetLoadRequest',
  full_name='bnet.protocol.server_pool.GetLoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=117,
  serialized_end=133,
)


_SERVERSTATE = descriptor.Descriptor(
  name='ServerState',
  full_name='bnet.protocol.server_pool.ServerState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='current_load', full_name='bnet.protocol.server_pool.ServerState.current_load', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='game_count', full_name='bnet.protocol.server_pool.ServerState.game_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='player_count', full_name='bnet.protocol.server_pool.ServerState.player_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=135,
  serialized_end=221,
)


_SERVERINFO = descriptor.Descriptor(
  name='ServerInfo',
  full_name='bnet.protocol.server_pool.ServerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='host', full_name='bnet.protocol.server_pool.ServerInfo.host', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='replace', full_name='bnet.protocol.server_pool.ServerInfo.replace', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='state', full_name='bnet.protocol.server_pool.ServerInfo.state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.server_pool.ServerInfo.attribute', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='program_id', full_name='bnet.protocol.server_pool.ServerInfo.program_id', index=4,
      number=5, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=224,
  serialized_end=430,
)


_POOLSTATEREQUEST = descriptor.Descriptor(
  name='PoolStateRequest',
  full_name='bnet.protocol.server_pool.PoolStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=432,
  serialized_end=450,
)


_POOLSTATERESPONSE = descriptor.Descriptor(
  name='PoolStateResponse',
  full_name='bnet.protocol.server_pool.PoolStateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='info', full_name='bnet.protocol.server_pool.PoolStateResponse.info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=452,
  serialized_end=524,
)

import lib.protocol.attribute_pb2
import lib.rpc.rpc_pb2

_SERVERINFO.fields_by_name['host'].message_type = lib.rpc.rpc_pb2._PROCESSID
_SERVERINFO.fields_by_name['state'].message_type = _SERVERSTATE
_SERVERINFO.fields_by_name['attribute'].message_type = lib.protocol.attribute_pb2._ATTRIBUTE
_POOLSTATERESPONSE.fields_by_name['info'].message_type = _SERVERINFO

class GetLoadRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETLOADREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.server_pool.GetLoadRequest)

class ServerState(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERSTATE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.server_pool.ServerState)

class ServerInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVERINFO
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.server_pool.ServerInfo)

class PoolStateRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POOLSTATEREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.server_pool.PoolStateRequest)

class PoolStateResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POOLSTATERESPONSE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.server_pool.PoolStateResponse)


_SERVERPOOLSERVICE = descriptor.ServiceDescriptor(
  name='ServerPoolService',
  full_name='bnet.protocol.server_pool.ServerPoolService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=526,
  serialized_end=652,
  methods=[
  descriptor.MethodDescriptor(
    name='GetPoolState',
    full_name='bnet.protocol.server_pool.ServerPoolService.GetPoolState',
    index=0,
    containing_service=None,
    input_type=_POOLSTATEREQUEST,
    output_type=_POOLSTATERESPONSE,
    options=None,
  ),
])

class ServerPoolService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _SERVERPOOLSERVICE
class ServerPoolService_Stub(ServerPoolService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _SERVERPOOLSERVICE

# @@protoc_insertion_point(module_scope)
