# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='OnlineService.proto',
  package='D3.OnlineService',
  serialized_pb='\n\x13OnlineService.proto\x12\x10\x44\x33.OnlineService\"+\n\x08\x45ntityId\x12\x0f\n\x07id_high\x18\x01 \x02(\x04\x12\x0e\n\x06id_low\x18\x02 \x02(\x04\":\n\x06GameId\x12\x0f\n\x07\x66\x61\x63tory\x18\x01 \x02(\x04\x12\x0f\n\x07id_high\x18\x02 \x02(\x04\x12\x0e\n\x06id_low\x18\x03 \x02(\x04\")\n\x06ItemId\x12\x0f\n\x07id_high\x18\x01 \x02(\x04\x12\x0e\n\x06id_low\x18\x02 \x02(\x04\"\xdb\x01\n\x10\x43oopCreateParams\x12\x18\n\x10\x64ifficulty_level\x18\x01 \x02(\x05\x12\x0b\n\x03\x61\x63t\x18\x02 \x02(\x11\x12\x11\n\tsno_quest\x18\x03 \x02(\x0f\x12\x15\n\rquest_step_id\x18\x04 \x02(\x05\x12<\n\x18resume_from_save_hero_id\x18\x05 \x01(\x0b\x32\x1a.D3.OnlineService.EntityId\x12\x17\n\x0fopen_to_friends\x18\x06 \x02(\x08\x12\x1f\n\x17open_to_friends_message\x18\x07 \x01(\t\"$\n\x0fPvPCreateParams\x12\x11\n\tsno_world\x18\x01 \x02(\x0f\"\xc1\x01\n\x10GameCreateParams\x12\x11\n\tgame_type\x18\x01 \x02(\x11\x12\x16\n\x0e\x63reation_flags\x18\x02 \x02(\r\x12\x30\n\x04\x63oop\x18\x03 \x01(\x0b\x32\".D3.OnlineService.CoopCreateParams\x12.\n\x03pvp\x18\x04 \x01(\x0b\x32!.D3.OnlineService.PvPCreateParams\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x12\n\nis_private\x18\x06 \x02(\x08\"N\n\x10HeroCreateParams\x12\x12\n\ngbid_class\x18\x01 \x02(\x0f\x12\x13\n\x0bis_hardcore\x18\x02 \x02(\x08\x12\x11\n\tis_female\x18\x03 \x02(\x08')




_ENTITYID = descriptor.Descriptor(
  name='EntityId',
  full_name='D3.OnlineService.EntityId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id_high', full_name='D3.OnlineService.EntityId.id_high', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id_low', full_name='D3.OnlineService.EntityId.id_low', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=41,
  serialized_end=84,
)


_GAMEID = descriptor.Descriptor(
  name='GameId',
  full_name='D3.OnlineService.GameId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='factory', full_name='D3.OnlineService.GameId.factory', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id_high', full_name='D3.OnlineService.GameId.id_high', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id_low', full_name='D3.OnlineService.GameId.id_low', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=86,
  serialized_end=144,
)


_ITEMID = descriptor.Descriptor(
  name='ItemId',
  full_name='D3.OnlineService.ItemId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id_high', full_name='D3.OnlineService.ItemId.id_high', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id_low', full_name='D3.OnlineService.ItemId.id_low', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=146,
  serialized_end=187,
)


_COOPCREATEPARAMS = descriptor.Descriptor(
  name='CoopCreateParams',
  full_name='D3.OnlineService.CoopCreateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='difficulty_level', full_name='D3.OnlineService.CoopCreateParams.difficulty_level', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='act', full_name='D3.OnlineService.CoopCreateParams.act', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='sno_quest', full_name='D3.OnlineService.CoopCreateParams.sno_quest', index=2,
      number=3, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='quest_step_id', full_name='D3.OnlineService.CoopCreateParams.quest_step_id', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='resume_from_save_hero_id', full_name='D3.OnlineService.CoopCreateParams.resume_from_save_hero_id', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='open_to_friends', full_name='D3.OnlineService.CoopCreateParams.open_to_friends', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='open_to_friends_message', full_name='D3.OnlineService.CoopCreateParams.open_to_friends_message', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=190,
  serialized_end=409,
)


_PVPCREATEPARAMS = descriptor.Descriptor(
  name='PvPCreateParams',
  full_name='D3.OnlineService.PvPCreateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='sno_world', full_name='D3.OnlineService.PvPCreateParams.sno_world', index=0,
      number=1, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=411,
  serialized_end=447,
)


_GAMECREATEPARAMS = descriptor.Descriptor(
  name='GameCreateParams',
  full_name='D3.OnlineService.GameCreateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='game_type', full_name='D3.OnlineService.GameCreateParams.game_type', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='creation_flags', full_name='D3.OnlineService.GameCreateParams.creation_flags', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='coop', full_name='D3.OnlineService.GameCreateParams.coop', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pvp', full_name='D3.OnlineService.GameCreateParams.pvp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='name', full_name='D3.OnlineService.GameCreateParams.name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_private', full_name='D3.OnlineService.GameCreateParams.is_private', index=5,
      number=6, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=450,
  serialized_end=643,
)


_HEROCREATEPARAMS = descriptor.Descriptor(
  name='HeroCreateParams',
  full_name='D3.OnlineService.HeroCreateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='gbid_class', full_name='D3.OnlineService.HeroCreateParams.gbid_class', index=0,
      number=1, type=15, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_hardcore', full_name='D3.OnlineService.HeroCreateParams.is_hardcore', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_female', full_name='D3.OnlineService.HeroCreateParams.is_female', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=645,
  serialized_end=723,
)


_COOPCREATEPARAMS.fields_by_name['resume_from_save_hero_id'].message_type = _ENTITYID
_GAMECREATEPARAMS.fields_by_name['coop'].message_type = _COOPCREATEPARAMS
_GAMECREATEPARAMS.fields_by_name['pvp'].message_type = _PVPCREATEPARAMS

class EntityId(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENTITYID
  
  # @@protoc_insertion_point(class_scope:D3.OnlineService.EntityId)

class GameId(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMEID
  
  # @@protoc_insertion_point(class_scope:D3.OnlineService.GameId)

class ItemId(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ITEMID
  
  # @@protoc_insertion_point(class_scope:D3.OnlineService.ItemId)

class CoopCreateParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COOPCREATEPARAMS
  
  # @@protoc_insertion_point(class_scope:D3.OnlineService.CoopCreateParams)

class PvPCreateParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PVPCREATEPARAMS
  
  # @@protoc_insertion_point(class_scope:D3.OnlineService.PvPCreateParams)

class GameCreateParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GAMECREATEPARAMS
  
  # @@protoc_insertion_point(class_scope:D3.OnlineService.GameCreateParams)

class HeroCreateParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROCREATEPARAMS
  
  # @@protoc_insertion_point(class_scope:D3.OnlineService.HeroCreateParams)

# @@protoc_insertion_point(module_scope)
