# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='PartyMessage.proto',
  package='D3.PartyMessage',
  serialized_pb='\n\x12PartyMessage.proto\x12\x0f\x44\x33.PartyMessage\x1a\x13OnlineService.proto\".\n\x0cScreenStatus\x12\x0e\n\x06screen\x18\x01 \x02(\x05\x12\x0e\n\x06status\x18\x02 \x02(\x05\"\x9a\x01\n\x19SearchForPublicGameParams\x12\x12\n\nstart_time\x18\x01 \x01(\x12\x12\x19\n\x11seconds_to_search\x18\x02 \x01(\r\x12\x37\n\x0bgame_params\x18\x03 \x01(\x0b\x32\".D3.OnlineService.GameCreateParams\x12\x15\n\rremove_reason\x18\x04 \x01(\x05')




_SCREENSTATUS = descriptor.Descriptor(
  name='ScreenStatus',
  full_name='D3.PartyMessage.ScreenStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='screen', full_name='D3.PartyMessage.ScreenStatus.screen', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status', full_name='D3.PartyMessage.ScreenStatus.status', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=106,
)


_SEARCHFORPUBLICGAMEPARAMS = descriptor.Descriptor(
  name='SearchForPublicGameParams',
  full_name='D3.PartyMessage.SearchForPublicGameParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='start_time', full_name='D3.PartyMessage.SearchForPublicGameParams.start_time', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='seconds_to_search', full_name='D3.PartyMessage.SearchForPublicGameParams.seconds_to_search', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='game_params', full_name='D3.PartyMessage.SearchForPublicGameParams.game_params', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='remove_reason', full_name='D3.PartyMessage.SearchForPublicGameParams.remove_reason', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=109,
  serialized_end=263,
)

import OnlineService_pb2

_SEARCHFORPUBLICGAMEPARAMS.fields_by_name['game_params'].message_type = OnlineService_pb2._GAMECREATEPARAMS

class ScreenStatus(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SCREENSTATUS
  
  # @@protoc_insertion_point(class_scope:D3.PartyMessage.ScreenStatus)

class SearchForPublicGameParams(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHFORPUBLICGAMEPARAMS
  
  # @@protoc_insertion_point(class_scope:D3.PartyMessage.SearchForPublicGameParams)

# @@protoc_insertion_point(module_scope)
