# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='lib/protocol/content_handle.proto',
  package='bnet.protocol',
  serialized_pb='\n!lib/protocol/content_handle.proto\x12\rbnet.protocol\"<\n\rContentHandle\x12\x0e\n\x06region\x18\x01 \x02(\x07\x12\r\n\x05usage\x18\x02 \x02(\x07\x12\x0c\n\x04hash\x18\x03 \x02(\x0c\x42\x10\x42\x0e\x43\x43ontentHandle')




_CONTENTHANDLE = descriptor.Descriptor(
  name='ContentHandle',
  full_name='bnet.protocol.ContentHandle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='region', full_name='bnet.protocol.ContentHandle.region', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usage', full_name='bnet.protocol.ContentHandle.usage', index=1,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='hash', full_name='bnet.protocol.ContentHandle.hash', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=112,
)



class ContentHandle(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTENTHANDLE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.ContentHandle)

# @@protoc_insertion_point(module_scope)
