# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='lib/protocol/descriptor.proto',
  package='bnet.protocol',
  serialized_pb='\n\x1dlib/protocol/descriptor.proto\x12\rbnet.protocol\"\x17\n\x04Path\x12\x0f\n\x07ordinal\x18\x01 \x03(\r')




_PATH = descriptor.Descriptor(
  name='Path',
  full_name='bnet.protocol.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ordinal', full_name='bnet.protocol.Path.ordinal', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=71,
)



class Path(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PATH
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.Path)

# @@protoc_insertion_point(module_scope)
