# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='lib/protocol/exchange.proto',
  package='bnet.protocol.exchange',
  serialized_pb='\n\x1blib/protocol/exchange.proto\x12\x16\x62net.protocol.exchange\"(\n\x0bPartitionId\x12\x0c\n\x04high\x18\x01 \x02(\x06\x12\x0b\n\x03low\x18\x02 \x02(\x06\"<\n\x08\x42lobFrom\x12\x0e\n\x06source\x18\x01 \x02(\x07\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\x12\x12\n\nextra_data\x18\x03 \x01(\x0c\"<\n\nBlobOfType\x12\x0c\n\x04type\x18\x01 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x12\n\nextra_data\x18\x03 \x01(\x0c\"<\n\x0e\x42lobFromOfType\x12\x0e\n\x06source\x18\x01 \x02(\x07\x12\x0c\n\x04type\x18\x02 \x02(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x0c\x42\x11\x42\x0c\x43\x45xchangeLib\x80\x01\x01')




_PARTITIONID = descriptor.Descriptor(
  name='PartitionId',
  full_name='bnet.protocol.exchange.PartitionId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='high', full_name='bnet.protocol.exchange.PartitionId.high', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='low', full_name='bnet.protocol.exchange.PartitionId.low', index=1,
      number=2, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=95,
)


_BLOBFROM = descriptor.Descriptor(
  name='BlobFrom',
  full_name='bnet.protocol.exchange.BlobFrom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='source', full_name='bnet.protocol.exchange.BlobFrom.source', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='bnet.protocol.exchange.BlobFrom.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='extra_data', full_name='bnet.protocol.exchange.BlobFrom.extra_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=157,
)


_BLOBOFTYPE = descriptor.Descriptor(
  name='BlobOfType',
  full_name='bnet.protocol.exchange.BlobOfType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='bnet.protocol.exchange.BlobOfType.type', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='bnet.protocol.exchange.BlobOfType.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='extra_data', full_name='bnet.protocol.exchange.BlobOfType.extra_data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=159,
  serialized_end=219,
)


_BLOBFROMOFTYPE = descriptor.Descriptor(
  name='BlobFromOfType',
  full_name='bnet.protocol.exchange.BlobFromOfType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='source', full_name='bnet.protocol.exchange.BlobFromOfType.source', index=0,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='bnet.protocol.exchange.BlobFromOfType.type', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='bnet.protocol.exchange.BlobFromOfType.data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=221,
  serialized_end=281,
)



class PartitionId(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PARTITIONID
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.exchange.PartitionId)

class BlobFrom(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOBFROM
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.exchange.BlobFrom)

class BlobOfType(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOBOFTYPE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.exchange.BlobOfType)

class BlobFromOfType(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BLOBFROMOFTYPE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.exchange.BlobFromOfType)

# @@protoc_insertion_point(module_scope)
