# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='lib/protocol/invitation.proto',
  package='bnet.protocol.invitation',
  serialized_pb='\n\x1dlib/protocol/invitation.proto\x12\x18\x62net.protocol.invitation\x1a\x1clib/protocol/attribute.proto\x1a\x19lib/protocol/entity.proto\"\xfd\x01\n\nInvitation\x12\n\n\x02id\x18\x01 \x02(\x06\x12\x31\n\x10inviter_identity\x18\x02 \x02(\x0b\x32\x17.bnet.protocol.Identity\x12\x31\n\x10invitee_identity\x18\x03 \x02(\x0b\x32\x17.bnet.protocol.Identity\x12\x14\n\x0cinviter_name\x18\x04 \x01(\t\x12\x14\n\x0cinvitee_name\x18\x05 \x01(\t\x12\x1a\n\x12invitation_message\x18\x06 \x01(\t\x12\x15\n\rcreation_time\x18\x07 \x01(\x04\x12\x17\n\x0f\x65xpiration_time\x18\x08 \x01(\x04*\x05\x08\x64\x10\x90N\"\xc7\x01\n\nSuggestion\x12+\n\nchannel_id\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12-\n\x0csuggester_id\x18\x02 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12-\n\x0csuggestee_id\x18\x03 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12\x16\n\x0esuggester_name\x18\x04 \x01(\t\x12\x16\n\x0esuggestee_name\x18\x05 \x01(\t\"\xb3\x01\n\x15SendInvitationRequest\x12/\n\x0e\x61gent_identity\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.Identity\x12*\n\ttarget_id\x18\x02 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12\x1a\n\x12invitation_message\x18\x03 \x01(\t\x12\x1a\n\x0f\x65xpiration_time\x18\x04 \x01(\x04:\x01\x30*\x05\x08\x64\x10\x90N\"R\n\x16SendInvitationResponse\x12\x38\n\ninvitation\x18\x02 \x01(\x0b\x32$.bnet.protocol.invitation.Invitation\"~\n\x0eGenericRequest\x12)\n\x08\x61gent_id\x18\x01 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12*\n\ttarget_id\x18\x02 \x01(\x0b\x32\x17.bnet.protocol.EntityId\x12\x15\n\rinvitation_id\x18\x03 \x02(\x06\x42\rB\x0b\x43Invitation')




_INVITATION = descriptor.Descriptor(
  name='Invitation',
  full_name='bnet.protocol.invitation.Invitation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='bnet.protocol.invitation.Invitation.id', index=0,
      number=1, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inviter_identity', full_name='bnet.protocol.invitation.Invitation.inviter_identity', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='invitee_identity', full_name='bnet.protocol.invitation.Invitation.invitee_identity', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='inviter_name', full_name='bnet.protocol.invitation.Invitation.inviter_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='invitee_name', full_name='bnet.protocol.invitation.Invitation.invitee_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='invitation_message', full_name='bnet.protocol.invitation.Invitation.invitation_message', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='creation_time', full_name='bnet.protocol.invitation.Invitation.creation_time', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expiration_time', full_name='bnet.protocol.invitation.Invitation.expiration_time', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 10000), ],
  serialized_start=117,
  serialized_end=370,
)


_SUGGESTION = descriptor.Descriptor(
  name='Suggestion',
  full_name='bnet.protocol.invitation.Suggestion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='channel_id', full_name='bnet.protocol.invitation.Suggestion.channel_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suggester_id', full_name='bnet.protocol.invitation.Suggestion.suggester_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suggestee_id', full_name='bnet.protocol.invitation.Suggestion.suggestee_id', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suggester_name', full_name='bnet.protocol.invitation.Suggestion.suggester_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suggestee_name', full_name='bnet.protocol.invitation.Suggestion.suggestee_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=373,
  serialized_end=572,
)


_SENDINVITATIONREQUEST = descriptor.Descriptor(
  name='SendInvitationRequest',
  full_name='bnet.protocol.invitation.SendInvitationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='agent_identity', full_name='bnet.protocol.invitation.SendInvitationRequest.agent_identity', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_id', full_name='bnet.protocol.invitation.SendInvitationRequest.target_id', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='invitation_message', full_name='bnet.protocol.invitation.SendInvitationRequest.invitation_message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='expiration_time', full_name='bnet.protocol.invitation.SendInvitationRequest.expiration_time', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(100, 10000), ],
  serialized_start=575,
  serialized_end=754,
)


_SENDINVITATIONRESPONSE = descriptor.Descriptor(
  name='SendInvitationResponse',
  full_name='bnet.protocol.invitation.SendInvitationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='invitation', full_name='bnet.protocol.invitation.SendInvitationResponse.invitation', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=756,
  serialized_end=838,
)


_GENERICREQUEST = descriptor.Descriptor(
  name='GenericRequest',
  full_name='bnet.protocol.invitation.GenericRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='agent_id', full_name='bnet.protocol.invitation.GenericRequest.agent_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target_id', full_name='bnet.protocol.invitation.GenericRequest.target_id', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='invitation_id', full_name='bnet.protocol.invitation.GenericRequest.invitation_id', index=2,
      number=3, type=6, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=840,
  serialized_end=966,
)

import lib.protocol.attribute_pb2
import lib.protocol.entity_pb2

_INVITATION.fields_by_name['inviter_identity'].message_type = lib.protocol.entity_pb2._IDENTITY
_INVITATION.fields_by_name['invitee_identity'].message_type = lib.protocol.entity_pb2._IDENTITY
_SUGGESTION.fields_by_name['channel_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_SUGGESTION.fields_by_name['suggester_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_SUGGESTION.fields_by_name['suggestee_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_SENDINVITATIONREQUEST.fields_by_name['agent_identity'].message_type = lib.protocol.entity_pb2._IDENTITY
_SENDINVITATIONREQUEST.fields_by_name['target_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_SENDINVITATIONRESPONSE.fields_by_name['invitation'].message_type = _INVITATION
_GENERICREQUEST.fields_by_name['agent_id'].message_type = lib.protocol.entity_pb2._ENTITYID
_GENERICREQUEST.fields_by_name['target_id'].message_type = lib.protocol.entity_pb2._ENTITYID

class Invitation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INVITATION
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.invitation.Invitation)

class Suggestion(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUGGESTION
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.invitation.Suggestion)

class SendInvitationRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENDINVITATIONREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.invitation.SendInvitationRequest)

class SendInvitationResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENDINVITATIONRESPONSE
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.invitation.SendInvitationResponse)

class GenericRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GENERICREQUEST
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.invitation.GenericRequest)

# @@protoc_insertion_point(module_scope)
