# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


DESCRIPTOR = descriptor.FileDescriptor(
  name='service/friends/friends_types.proto',
  package='bnet.protocol.friends',
  serialized_pb='\n#service/friends/friends_types.proto\x12\x15\x62net.protocol.friends\x1a\x1clib/protocol/attribute.proto\x1a\x19lib/protocol/entity.proto\x1a\x1dlib/protocol/invitation.proto\"d\n\x06\x46riend\x12#\n\x02id\x18\x01 \x02(\x0b\x32\x17.bnet.protocol.EntityId\x12\x35\n\tattribute\x18\x02 \x03(\x0b\x32\".bnet.protocol.attribute.Attribute\"\x9b\x01\n\x10\x46riendInvitation\x12\x1d\n\x0e\x66irst_received\x18\x01 \x01(\x08:\x05\x66\x61lse2h\n\x11\x66riend_invitation\x12$.bnet.protocol.invitation.Invitation\x18g \x01(\x0b\x32\'.bnet.protocol.friends.FriendInvitation')




_FRIEND = descriptor.Descriptor(
  name='Friend',
  full_name='bnet.protocol.friends.Friend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='bnet.protocol.friends.Friend.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attribute', full_name='bnet.protocol.friends.Friend.attribute', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=150,
  serialized_end=250,
)


_FRIENDINVITATION = descriptor.Descriptor(
  name='FriendInvitation',
  full_name='bnet.protocol.friends.FriendInvitation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='first_received', full_name='bnet.protocol.friends.FriendInvitation.first_received', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='friend_invitation', full_name='bnet.protocol.friends.FriendInvitation.friend_invitation', index=0,
      number=103, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=253,
  serialized_end=408,
)

import lib.protocol.attribute_pb2
import lib.protocol.entity_pb2
import lib.protocol.invitation_pb2

_FRIEND.fields_by_name['id'].message_type = lib.protocol.entity_pb2._ENTITYID
_FRIEND.fields_by_name['attribute'].message_type = lib.protocol.attribute_pb2._ATTRIBUTE

class Friend(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRIEND
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.friends.Friend)

class FriendInvitation(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FRIENDINVITATION
  
  # @@protoc_insertion_point(class_scope:bnet.protocol.friends.FriendInvitation)

_FRIENDINVITATION.extensions_by_name['friend_invitation'].message_type = _FRIENDINVITATION
lib.protocol.invitation_pb2.Invitation.RegisterExtension(_FRIENDINVITATION.extensions_by_name['friend_invitation'])
# @@protoc_insertion_point(module_scope)
